#!/usr/bin/env bash
# A script that configures an Ubuntu server wiht the below requiremenii.
# Copy the original hosts file to a new location

cp /etc/hosts ~/hosts.Dorcas
echo "localhost 127.0.0.2" >> ~/hosts.Dorcas
echo "8.8.8.8 facebook.com" >> ~/hosts.Dorcas
cp -f ~/hosts.Dorcas /etc/hosts

